exclude_paths:
- "versioneer.py"
- "microsoft_auth/_version.py"
- "config"
- "db"
- "dist"
- "features"
- "**/node_modules"
- "script"
- "**/spec"
- "**/test"
- "**/tests"
- "**/vendor"
- "**/*.d.ts"
